language: android

env:
  global:
  - secure: nyzov/BzxeU7UPWaEug/LnXMtj7sbEhKDFHczQtxlg0eTCJLzQWRLOomDFxLtxnkxBckvnN2JK4dcpKwpXedaXEj6uVFskBeSEe02hckWJsUNPeUNR+EJPsU0PVbMrhEKyVtQR6eC8UiloTNCNsKrCx70Cxpe1dBN1QvrRVkadwV2K0zols5iZB1ncSTWTcVdzJBsqluUb9SqGGlAii/Yzq+hSZiRFdRj8yePZtvfAB6nqhHSl5f7jZmHA7HTxhKqteiYvFNhUMHvjrY6OAWcquSoI8i8TdWTsi51c8uucFeaKJpuYEHWViOOF4iTdQZ+sPUibmLshhDdpqCyGV5L5zDGeejgLO/6lO5yasv5L6+X2SyH7RiJSt0Jfg7a2AMkFh/+SgagDxZ2jJA/UPHyGWbNbGVE0IiO+0XStHvXtBLs1hhqsSD/novYxYtGfsJfw+KajE3LEdGqNCeiFwpZadTRaopGNL5qViHMM1Ix+oWGtb0QR9yAoHumf5vN0LSWcfZWUEGwJcmOLfTvEL5RI5IwNQeYIfHfgBt+2nmpqwpHuIaotQh90yR0+IDF2YNUyYDx5i6WQLGQ9SIxODZZ1+mNUbu+6RBCRzqOqtZYl9cVjYLFzcLb8rNKq7EzY7T+JerHWI5Id4bpttPx6APEMoKX/hKKvJCZN1bY0UzvHQ=
  - secure: TAe5wd9yhWfASeUt0TtJqe6geJFjMwsYy4MHtBSJELL9DeEBxODnV1Q4rEZWZWf8IscR7nYLruzot5Dvgmxsr+4HEM3K1TLT0grxXThVfYiKVcbnWj7NHzOT2m67GtU63af0Cngj6lbqxGzIZu3EDnqVbfdBcK6opnUHnGGOJJ50Mxhn67NG3S6TZewSwzTtpzrlXV0zKKIPzJtmVOX+JYpKfrQmtY0XSv+Ihnge7boUY/q/eaPXGeu24NF2kVIvAbImvVCccbztXeD1APJzzh9B0cybtWt+hkvlTuDpoT5yby+ZCoTRBQdUheYoTDHul+QShms+K8ngNwIzfIzEYrtvJEl4D5JHsoXIMDPIjoYL5f9DrOQMzRzpaqnFXuW5vUnzBwu/Up6QxVWs4Kgl+YjcP0ItQmAvcjM835LfynHSJvFXDFGVM96cAhtyXo1e+/ITeRhmMFFTzLs+cQJHHlXLKctF3M/I2qcHNqIobUzfnfP3C7gQzMGzxvCgzFoeGghjqPYCKu5FHxwKh0pplU7u3b8egkElfVJt86IeSmgcqE9BFz1aoXfi7i+8VvKDUbIXUMJMze5pZPaX2JEH5QUY1ZIMbAQBDiZihhYYUWSRObgzKx1fC0bnwm+/FmEpNMBMqxrX70eWL7L0Tz/yOJ7qXNzLUhBX43+QmXK58/E=

script:
- gradle test

after_success:
- scripts/deploy.sh
